# lab08 - Tensor Manipulation

In [7]:
import numpy as np
import tensorflow as tf

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

print(t)
print(t.ndim)    # rank
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:4], t[4:-1])
print(t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 1.0 6.0
[2. 3.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [6]:
t = np.array([[1.,  2.,  3.],
              [4.,  5.,  6.],
              [7.,  8.,  9.],
              [10., 11., 12.]])

print(t)
print(t.ndim)
print(t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


In [12]:
t = tf.constant([1, 2, 3, 4])
print(tf.shape(t))

tf.Tensor([4], shape=(1,), dtype=int32)


In [14]:
t = tf.constant([[1, 2],
                 [3, 4]])
print(tf.shape(t))

tf.Tensor([2 2], shape=(2,), dtype=int32)


In [15]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(tf.shape(t))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


[

    [
    
        [
        
            [1, 2, 3, 4],
            
            [5, 6, 7, 8],
            
            [9, 10, 11, 12]
        
        ],
        
        [
        
            [13, 14, 15, 16],
            
            [17, 18, 19, 20],
            
            [21, 22, 23, 24]
        
        ]
        
    ]
    
]

rank == 4이므로 axis도 4개

가장 바깥에 있는 축이 axis = 0

제일 안쪽에 있는 축이 axis = 3 또는 axis = -1

In [19]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("matrix 1 shape: ", matrix1.shape)
print("matrix 2 shape: ", matrix2.shape)
print('\n\n')

print(tf.matmul(matrix1, matrix2))
print('\n\n')

print(matrix1 * matrix2)

matrix 1 shape:  (2, 2)
matrix 2 shape:  (2, 1)



tf.Tensor(
[[ 5.]
 [11.]], shape=(2, 1), dtype=float32)



tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)


## Broadcasting

shape이 달라도 연산이 가능하도록 하게 함

In [20]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 3.]])
print(matrix1 + matrix2)



tf.Tensor([[5. 6.]], shape=(1, 2), dtype=float32)


In [21]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)         # [[3, 3]]
print(matrix1 + matrix2)

tf.Tensor([[4. 5.]], shape=(1, 2), dtype=float32)


In [22]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3., 4.]])
print(matrix1 + matrix2)

tf.Tensor([[4. 6.]], shape=(1, 2), dtype=float32)


In [23]:
matrix1 = tf.constant([[1., 2.]])    # [[1, 2], [1, 2]]
matrix2 = tf.constant([[3.], [4.]])  # [[3, 3], [4, 4]]
print(matrix1 + matrix2)

tf.Tensor(
[[4. 5.]
 [5. 6.]], shape=(2, 2), dtype=float32)


## reduce mean

In [25]:
print(tf.reduce_mean([1, 2], axis=0))
print(tf.reduce_mean([1., 2.], axis=0))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.5, shape=(), dtype=float32)


In [29]:
x = [[1., 2.],
     [3., 4.]]

print(tf.reduce_mean(x))
print('\n')

print(tf.reduce_mean(x, axis=0))

print(tf.reduce_mean(x, axis=1))

print(tf.reduce_mean(x, axis=-1))

tf.Tensor(2.5, shape=(), dtype=float32)


tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


## reduce sum

In [41]:
x = [[1., 2.],
     [3., 4.]]

print(tf.reduce_sum(x))
print('\n')

print(tf.reduce_sum(x, axis=0).numpy())

print(tf.reduce_sum(x, axis=1).numpy())

print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)).numpy())

tf.Tensor(10.0, shape=(), dtype=float32)


[4. 6.]
[3. 7.]
5.0


## argmax

가장 큰 값의 index

In [44]:
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.argmax(x, axis=0).numpy())

[1 0 0]


In [46]:
print(tf.argmax(x, axis=1).numpy())
print(tf.argmax(x, axis=-1).numpy())

[2 0]
[2 0]


In [50]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              
              [[6, 7, 8],
               [9, 10, 11]]])

print(t.shape)
print('\n')

# rank=2, [알아서, 3]의 형태로
print(tf.reshape(t, shape=[-1, 3]).numpy())
print('\n')

# rank=3, [알아서, 1, 3]의 형태로
print(tf.reshape(t, shape=[-1, 1, 3]).numpy())

(2, 2, 3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]


## reshape(squeeze, expand)

In [52]:
print(tf.squeeze([[0], [1], [2]]).numpy())

print(tf.expand_dims([0, 1, 2], 1).numpy())

[0 1 2]
[[0]
 [1]
 [2]]


## one hot

In [55]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)

# one hot이 rank를 자동으로 1만큼 expand
print(t.numpy())
print('\n')

print(tf.reshape(t, shape=[-1, 3]).numpy())

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [57]:
tf.one_hot([[0], [1], [2], [0]], depth=4).numpy()

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[1., 0., 0., 0.]]], dtype=float32)

## casting

In [59]:
# integer로 바꿈
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy())
print('\n')

print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).numpy())

[1 2 3 4]


[1 0 1 0]


## stack

In [61]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# pack along first dim
print(tf.stack([x, y, z]).numpy())
print('\n')

print(tf.stack([x, y, z], axis=1).numpy())
print('\n')

print(tf.stack([x, y, z], axis=0).numpy())

[[1 4]
 [2 5]
 [3 6]]


[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


## ones and zeros like

In [63]:
x = [[0, 1, 2], 
     [2, 1, 0]]

print(tf.ones_like(x).numpy())
print('\n')

print(tf.zeros_like(x).numpy())

[[1 1 1]
 [1 1 1]]


[[0 0 0]
 [0 0 0]]


## zip

In [65]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)
    
print('\n\n')

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6



1 4 7
2 5 8
3 6 9
