# lab06 - Sotfmax Classfier

In [21]:
import numpy as np
import tensorflow as tf

In [24]:
x_rax = [[1, 2, 1, 1], 
         [2, 1, 3, 2],
         [3, 1, 3, 4],
         [4, 1, 5, 5],
         [1, 7, 5, 5],
         [1, 2, 5, 6],
         [1, 6, 6, 6],
         [1, 7, 7, 7]]
y_rax = [[0, 0, 1],
         [0, 0, 1],
         [0, 0, 1],
         [0, 1, 0],
         [0, 1, 0],
         [0, 1, 0],
         [1, 0, 0],
         [1, 0, 0]]

x_data = np.array(x_rax, dtype=np.float32)
y_data = np.array(y_rax, dtype=np.float32)

nb_classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=4, use_bias=True))  # use_bias=True, bu default
# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
# logit = tf.matmul(X, W) + b
tf.model.add(tf.keras.layers.Activation('softmax'))

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_data, epochs=2000)

print('--------------------')
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

print('--------------------')
b = tf.model.predict(np.array([[1, 5, 3, 4]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

print('------------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
print(c, tf.keras.backend.eval(tf.argmax(c, axis=1)))

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 3)                 15        
_________________________________________________________________
activation_1 (Activation)    (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
Epoch 1/2000
1/1 [==============================] - 0s 2ms/step - loss: 4.7863 - accuracy: 0.3750
Epoch 2/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.8824 - accuracy: 0.1250
Epoch 3/2000
1/1 [==============================] - 0s 3ms/step - loss: 1.6760 - accuracy: 0.1250
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5064 - accuracy: 0.1250
Epoch 5/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.3711 - accuracy: 0.1250
Epoch 6/2000
1/1 [============

1/1 [==============================] - 0s 997us/step - loss: 0.7524 - accuracy: 0.6250
Epoch 78/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6890 - accuracy: 0.6250
Epoch 79/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.7486 - accuracy: 0.6250
Epoch 80/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6856 - accuracy: 0.6250
Epoch 81/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.7450 - accuracy: 0.6250
Epoch 82/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6822 - accuracy: 0.6250
Epoch 83/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.7414 - accuracy: 0.6250
Epoch 84/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6790 - accuracy: 0.6250
Epoch 85/2000
1/1 [==============================] - 0s 996us/step - loss: 0.7381 - accuracy: 0.6250
Epoch 86/2000
1/1 [==============================] - 0s 998us/step - loss: 0.6759 - accuracy: 0.6250
Epoch 87/2000
1/1 

1/1 [==============================] - 0s 998us/step - loss: 0.6012 - accuracy: 0.6250
Epoch 159/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6607 - accuracy: 0.6250
Epoch 160/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5997 - accuracy: 0.6250
Epoch 161/2000
1/1 [==============================] - 0s 984us/step - loss: 0.6592 - accuracy: 0.6250
Epoch 162/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5982 - accuracy: 0.6250
Epoch 163/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6577 - accuracy: 0.6250
Epoch 164/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5967 - accuracy: 0.6250
Epoch 165/2000
1/1 [==============================] - 0s 998us/step - loss: 0.6563 - accuracy: 0.6250
Epoch 166/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5952 - accuracy: 0.6250
Epoch 167/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.6548 - accuracy: 0.6250
Epoch

1/1 [==============================] - 0s 998us/step - loss: 0.6093 - accuracy: 0.6250
Epoch 240/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5488 - accuracy: 0.6250
Epoch 241/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6081 - accuracy: 0.6250
Epoch 242/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5477 - accuracy: 0.6250
Epoch 243/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6070 - accuracy: 0.6250
Epoch 244/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5466 - accuracy: 0.6250
Epoch 245/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.6058 - accuracy: 0.6250
Epoch 246/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5455 - accuracy: 0.6250
Epoch 247/2000
1/1 [==============================] - 0s 997us/step - loss: 0.6047 - accuracy: 0.6250
Epoch 248/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5445 - accuracy: 0.6250
Epoch 2

1/1 [==============================] - 0s 2ms/step - loss: 0.5087 - accuracy: 0.7500
Epoch 321/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5653 - accuracy: 0.6250
Epoch 322/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5078 - accuracy: 0.7500
Epoch 323/2000
1/1 [==============================] - 0s 996us/step - loss: 0.5642 - accuracy: 0.6250
Epoch 324/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5068 - accuracy: 0.7500
Epoch 325/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5632 - accuracy: 0.6250
Epoch 326/2000
1/1 [==============================] - 0s 993us/step - loss: 0.5059 - accuracy: 0.7500
Epoch 327/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.5622 - accuracy: 0.6250
Epoch 328/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5050 - accuracy: 0.7500
Epoch 329/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5612 - accuracy: 0.6250
Epoch 330

1/1 [==============================] - 0s 2ms/step - loss: 0.5258 - accuracy: 0.8750
Epoch 402/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4730 - accuracy: 0.7500
Epoch 403/2000
1/1 [==============================] - 0s 996us/step - loss: 0.5249 - accuracy: 0.8750
Epoch 404/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4722 - accuracy: 0.7500
Epoch 405/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5239 - accuracy: 0.8750
Epoch 406/2000
1/1 [==============================] - 0s 986us/step - loss: 0.4714 - accuracy: 0.7500
Epoch 407/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5229 - accuracy: 0.8750
Epoch 408/2000
1/1 [==============================] - 0s 996us/step - loss: 0.4705 - accuracy: 0.7500
Epoch 409/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5220 - accuracy: 0.8750
Epoch 410/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4697 - accuracy: 0.7500
Epoch

1/1 [==============================] - 0s 1ms/step - loss: 0.4413 - accuracy: 0.7500
Epoch 483/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.4871 - accuracy: 0.8750
Epoch 484/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4405 - accuracy: 0.7500
Epoch 485/2000
1/1 [==============================] - 0s 991us/step - loss: 0.4862 - accuracy: 0.8750
Epoch 486/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4398 - accuracy: 0.7500
Epoch 487/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4852 - accuracy: 0.8750
Epoch 488/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4390 - accuracy: 0.7500
Epoch 489/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4843 - accuracy: 0.8750
Epoch 490/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4382 - accuracy: 0.7500
Epoch 491/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4834 - accuracy: 0.8750
Epoch 492

1/1 [==============================] - 0s 2ms/step - loss: 0.4502 - accuracy: 0.8750
Epoch 564/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4108 - accuracy: 0.7500
Epoch 565/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4493 - accuracy: 0.8750
Epoch 566/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4100 - accuracy: 0.7500
Epoch 567/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4484 - accuracy: 0.8750
Epoch 568/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4093 - accuracy: 0.7500
Epoch 569/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.8750
Epoch 570/2000
1/1 [==============================] - 0s 984us/step - loss: 0.4086 - accuracy: 0.7500
Epoch 571/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.4465 - accuracy: 0.8750
Epoch 572/2000
1/1 [==============================] - 0s 999us/step - loss: 0.4079 - accuracy: 0.7500
Epoch 5

Epoch 644/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3821 - accuracy: 0.8750
Epoch 645/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4128 - accuracy: 0.8750
Epoch 646/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3814 - accuracy: 0.8750
Epoch 647/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4119 - accuracy: 0.8750
Epoch 648/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3807 - accuracy: 0.8750
Epoch 649/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4110 - accuracy: 0.8750
Epoch 650/2000
1/1 [==============================] - 0s 990us/step - loss: 0.3800 - accuracy: 0.8750
Epoch 651/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8750
Epoch 652/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3793 - accuracy: 0.8750
Epoch 653/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.4092 - accu

1/1 [==============================] - 0s 2ms/step - loss: 0.3765 - accuracy: 0.8750
Epoch 726/2000
1/1 [==============================] - 0s 996us/step - loss: 0.3532 - accuracy: 0.8750
Epoch 727/2000
1/1 [==============================] - 0s 991us/step - loss: 0.3756 - accuracy: 0.8750
Epoch 728/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3525 - accuracy: 0.8750
Epoch 729/2000
1/1 [==============================] - 0s 996us/step - loss: 0.3747 - accuracy: 0.8750
Epoch 730/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.3518 - accuracy: 0.8750
Epoch 731/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3737 - accuracy: 0.8750
Epoch 732/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8750
Epoch 733/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3728 - accuracy: 0.8750
Epoch 734/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3504 - accuracy: 0.8750
Epoc

1/1 [==============================] - 0s 2ms/step - loss: 0.3249 - accuracy: 0.8750
Epoch 807/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3393 - accuracy: 0.8750
Epoch 808/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3242 - accuracy: 0.8750
Epoch 809/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3384 - accuracy: 0.8750
Epoch 810/2000
1/1 [==============================] - 0s 965us/step - loss: 0.3235 - accuracy: 0.8750
Epoch 811/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3375 - accuracy: 0.8750
Epoch 812/2000
1/1 [==============================] - 0s 0s/step - loss: 0.3228 - accuracy: 0.8750
Epoch 813/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3366 - accuracy: 0.8750
Epoch 814/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3221 - accuracy: 0.8750
Epoch 815/2000
1/1 [==============================] - 0s 988us/step - loss: 0.3357 - accuracy: 0.8750
Epoch 816/20

1/1 [==============================] - 0s 2ms/step - loss: 0.3033 - accuracy: 0.8750
Epoch 888/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2954 - accuracy: 0.8750
Epoch 889/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3024 - accuracy: 0.8750
Epoch 890/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2947 - accuracy: 0.8750
Epoch 891/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3015 - accuracy: 0.8750
Epoch 892/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2939 - accuracy: 0.8750
Epoch 893/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3007 - accuracy: 0.8750
Epoch 894/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2932 - accuracy: 0.8750
Epoch 895/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2998 - accuracy: 0.8750
Epoch 896/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2925 - accuracy: 0.8750
Epoch 8

1/1 [==============================] - 0s 3ms/step - loss: 0.2665 - accuracy: 1.0000
Epoch 969/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2682 - accuracy: 0.8750
Epoch 970/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2658 - accuracy: 1.0000
Epoch 971/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2674 - accuracy: 0.8750
Epoch 972/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2651 - accuracy: 1.0000
Epoch 973/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2666 - accuracy: 0.8750
Epoch 974/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2644 - accuracy: 1.0000
Epoch 975/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2658 - accuracy: 0.8750
Epoch 976/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2637 - accuracy: 1.0000
Epoch 977/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2650 - accuracy: 0.8750
Epoch 978/2

1/1 [==============================] - 0s 995us/step - loss: 0.2433 - accuracy: 1.0000
Epoch 1049/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2432 - accuracy: 1.0000
Epoch 1050/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2429 - accuracy: 1.0000
Epoch 1051/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2428 - accuracy: 1.0000
Epoch 1052/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2426 - accuracy: 1.0000
Epoch 1053/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2424 - accuracy: 1.0000
Epoch 1054/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2422 - accuracy: 1.0000
Epoch 1055/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2420 - accuracy: 1.0000
Epoch 1056/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2418 - accuracy: 1.0000
Epoch 1057/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2417 - accuracy: 1.0000
Ep

1/1 [==============================] - 0s 2ms/step - loss: 0.2322 - accuracy: 1.0000
Epoch 1129/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2321 - accuracy: 1.0000
Epoch 1130/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2320 - accuracy: 1.0000
Epoch 1131/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2319 - accuracy: 1.0000
Epoch 1132/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2318 - accuracy: 1.0000
Epoch 1133/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2317 - accuracy: 1.0000
Epoch 1134/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2315 - accuracy: 1.0000
Epoch 1135/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2314 - accuracy: 1.0000
Epoch 1136/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2313 - accuracy: 1.0000
Epoch 1137/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2312 - accuracy: 1.000

1/1 [==============================] - 0s 997us/step - loss: 0.2232 - accuracy: 1.0000
Epoch 1209/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2231 - accuracy: 1.0000
Epoch 1210/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2230 - accuracy: 1.0000
Epoch 1211/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2229 - accuracy: 1.0000
Epoch 1212/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2228 - accuracy: 1.0000
Epoch 1213/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2227 - accuracy: 1.0000
Epoch 1214/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2226 - accuracy: 1.0000
Epoch 1215/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2225 - accuracy: 1.0000
Epoch 1216/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2223 - accuracy: 1.0000
Epoch 1217/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2222 - accuracy: 1

1/1 [==============================] - 0s 0s/step - loss: 0.2148 - accuracy: 1.0000
Epoch 1289/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2147 - accuracy: 1.0000
Epoch 1290/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2146 - accuracy: 1.0000
Epoch 1291/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2145 - accuracy: 1.0000
Epoch 1292/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2144 - accuracy: 1.0000
Epoch 1293/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2143 - accuracy: 1.0000
Epoch 1294/2000
1/1 [==============================] - 0s 987us/step - loss: 0.2142 - accuracy: 1.0000
Epoch 1295/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2141 - accuracy: 1.0000
Epoch 1296/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2140 - accuracy: 1.0000
Epoch 1297/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2139 - accuracy: 1.00

1/1 [==============================] - 0s 997us/step - loss: 0.2070 - accuracy: 1.0000
Epoch 1369/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2069 - accuracy: 1.0000
Epoch 1370/2000
1/1 [==============================] - 0s 0s/step - loss: 0.2069 - accuracy: 1.0000
Epoch 1371/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2068 - accuracy: 1.0000
Epoch 1372/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2067 - accuracy: 1.0000
Epoch 1373/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2066 - accuracy: 1.0000
Epoch 1374/2000
1/1 [==============================] - 0s 978us/step - loss: 0.2065 - accuracy: 1.0000
Epoch 1375/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.2064 - accuracy: 1.0000
Epoch 1376/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2063 - accuracy: 1.0000
Epoch 1377/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2062 - accuracy: 1.

1/1 [==============================] - 0s 1ms/step - loss: 0.1998 - accuracy: 1.0000
Epoch 1449/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1997 - accuracy: 1.0000
Epoch 1450/2000
1/1 [==============================] - 0s 983us/step - loss: 0.1996 - accuracy: 1.0000
Epoch 1451/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1995 - accuracy: 1.0000
Epoch 1452/2000
1/1 [==============================] - 0s 996us/step - loss: 0.1994 - accuracy: 1.0000
Epoch 1453/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1993 - accuracy: 1.0000
Epoch 1454/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1992 - accuracy: 1.0000
Epoch 1455/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1992 - accuracy: 1.0000
Epoch 1456/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1991 - accuracy: 1.0000
Epoch 1457/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1990 - accuracy: 1.0

1/1 [==============================] - 0s 2ms/step - loss: 0.1930 - accuracy: 1.0000
Epoch 1529/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1929 - accuracy: 1.0000
Epoch 1530/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1928 - accuracy: 1.0000
Epoch 1531/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1927 - accuracy: 1.0000
Epoch 1532/2000
1/1 [==============================] - 0s 985us/step - loss: 0.1926 - accuracy: 1.0000
Epoch 1533/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1926 - accuracy: 1.0000
Epoch 1534/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1925 - accuracy: 1.0000
Epoch 1535/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1924 - accuracy: 1.0000
Epoch 1536/2000
1/1 [==============================] - 0s 995us/step - loss: 0.1923 - accuracy: 1.0000
Epoch 1537/2000
1/1 [==============================] - 0s 999us/step - loss: 0.1922 - accuracy: 1

1/1 [==============================] - 0s 996us/step - loss: 0.1866 - accuracy: 1.0000
Epoch 1609/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1865 - accuracy: 1.0000
Epoch 1610/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1864 - accuracy: 1.0000
Epoch 1611/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1864 - accuracy: 1.0000
Epoch 1612/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1863 - accuracy: 1.0000
Epoch 1613/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1862 - accuracy: 1.0000
Epoch 1614/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1861 - accuracy: 1.0000
Epoch 1615/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1861 - accuracy: 1.0000
Epoch 1616/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1860 - accuracy: 1.0000
Epoch 1617/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1859 - accuracy: 1.0000


1/1 [==============================] - 0s 998us/step - loss: 0.1806 - accuracy: 1.0000
Epoch 1689/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1805 - accuracy: 1.0000
Epoch 1690/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1805 - accuracy: 1.0000
Epoch 1691/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.1804 - accuracy: 1.0000
Epoch 1692/2000
1/1 [==============================] - 0s 990us/step - loss: 0.1803 - accuracy: 1.0000
Epoch 1693/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1803 - accuracy: 1.0000
Epoch 1694/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1802 - accuracy: 1.0000
Epoch 1695/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1801 - accuracy: 1.0000
Epoch 1696/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1800 - accuracy: 1.0000
Epoch 1697/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1800 - accuracy: 1.0000

1/1 [==============================] - 0s 997us/step - loss: 0.1750 - accuracy: 1.0000
Epoch 1769/2000
1/1 [==============================] - 0s 999us/step - loss: 0.1749 - accuracy: 1.0000
Epoch 1770/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1749 - accuracy: 1.0000
Epoch 1771/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1748 - accuracy: 1.0000
Epoch 1772/2000
1/1 [==============================] - 0s 995us/step - loss: 0.1747 - accuracy: 1.0000
Epoch 1773/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1746 - accuracy: 1.0000
Epoch 1774/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1746 - accuracy: 1.0000
Epoch 1775/2000
1/1 [==============================] - 0s 999us/step - loss: 0.1745 - accuracy: 1.0000
Epoch 1776/2000
1/1 [==============================] - 0s 999us/step - loss: 0.1744 - accuracy: 1.0000
Epoch 1777/2000
1/1 [==============================] - 0s 997us/step - loss: 0.1744 - accuracy: 1

1/1 [==============================] - 0s 2ms/step - loss: 0.1697 - accuracy: 1.0000
Epoch 1849/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1696 - accuracy: 1.0000
Epoch 1850/2000
1/1 [==============================] - 0s 996us/step - loss: 0.1696 - accuracy: 1.0000
Epoch 1851/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1695 - accuracy: 1.0000
Epoch 1852/2000
1/1 [==============================] - 0s 964us/step - loss: 0.1694 - accuracy: 1.0000
Epoch 1853/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1694 - accuracy: 1.0000
Epoch 1854/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1693 - accuracy: 1.0000
Epoch 1855/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1692 - accuracy: 1.0000
Epoch 1856/2000
1/1 [==============================] - 0s 0s/step - loss: 0.1692 - accuracy: 1.0000
Epoch 1857/2000
1/1 [==============================] - 0s 3ms/step - loss: 0.1691 - accuracy: 1.0000
E

1/1 [==============================] - 0s 996us/step - loss: 0.1647 - accuracy: 1.0000
Epoch 1929/2000
1/1 [==============================] - 0s 998us/step - loss: 0.1646 - accuracy: 1.0000
Epoch 1930/2000
1/1 [==============================] - 0s 995us/step - loss: 0.1646 - accuracy: 1.0000
Epoch 1931/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.1645 - accuracy: 1.0000
Epoch 1932/2000
1/1 [==============================] - 0s 993us/step - loss: 0.1644 - accuracy: 1.0000
Epoch 1933/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1644 - accuracy: 1.0000
Epoch 1934/2000
1/1 [==============================] - 0s 994us/step - loss: 0.1643 - accuracy: 1.0000
Epoch 1935/2000
1/1 [==============================] - 0s 996us/step - loss: 0.1643 - accuracy: 1.0000
Epoch 1936/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.1642 - accuracy: 1.0000
Epoch 1937/2000
1/1 [==============================] - 0s 995us/step - loss: 0.1641 - accuracy:

In [27]:
# Predicting animal type based on various features
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

nb_classes = 7

# Conver y_data to one_hot
# tf.keras.utils.to_categorical: Converts a class vector (integers) to binary class matrix.
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one hot: ", y_one_hot)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=x_data.shape[1], activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_one_hot, epochs=1000)

# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]])  # expected prediction == 3 (feathers)
pred = tf.model.predict(test_data)
print(pred)
print(tf.model.predict_classes(test_data))
#print(pred, tf.keras.backend.eval(tf.argmax(pred, axis=1)))

# Full x_data test
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

(101, 16) (101, 1)
one hot:  [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 

4/4 [==============================] - 0s 1ms/step - loss: 0.3144 - accuracy: 0.9208
Epoch 54/1000
4/4 [==============================] - 0s 998us/step - loss: 0.3098 - accuracy: 0.9307
Epoch 55/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.3054 - accuracy: 0.9307
Epoch 56/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.3034 - accuracy: 0.9208
Epoch 57/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.3017 - accuracy: 0.9208
Epoch 58/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2978 - accuracy: 0.9208
Epoch 59/1000
4/4 [==============================] - 0s 746us/step - loss: 0.2936 - accuracy: 0.9307
Epoch 60/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2927 - accuracy: 0.9307
Epoch 61/1000
4/4 [==============================] - 0s 998us/step - loss: 0.2878 - accuracy: 0.9307
Epoch 62/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.2849 - accuracy: 0.9307
Epoch 63/1000
4/4 

4/4 [==============================] - 0s 1ms/step - loss: 0.1666 - accuracy: 0.9703
Epoch 135/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1663 - accuracy: 0.9703
Epoch 136/1000
4/4 [==============================] - 0s 995us/step - loss: 0.1656 - accuracy: 0.9703
Epoch 137/1000
4/4 [==============================] - 0s 994us/step - loss: 0.1658 - accuracy: 0.9703
Epoch 138/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1662 - accuracy: 0.9703
Epoch 139/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1651 - accuracy: 0.9703
Epoch 140/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1635 - accuracy: 0.9703
Epoch 141/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1616 - accuracy: 0.9703
Epoch 142/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1614 - accuracy: 0.9802
Epoch 143/1000
4/4 [==============================] - 0s 748us/step - loss: 0.1600 - accuracy: 0.9802
Epoch 144

4/4 [==============================] - 0s 1ms/step - loss: 0.1175 - accuracy: 0.9802
Epoch 216/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1153 - accuracy: 1.0000
Epoch 217/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1144 - accuracy: 1.0000
Epoch 218/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1145 - accuracy: 1.0000
Epoch 219/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.1130 - accuracy: 1.0000
Epoch 220/1000
4/4 [==============================] - 0s 993us/step - loss: 0.1138 - accuracy: 1.0000
Epoch 221/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1130 - accuracy: 0.9901
Epoch 222/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1125 - accuracy: 1.0000
Epoch 223/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.1125 - accuracy: 0.9901
Epoch 224/1000
4/4 [==============================] - 0s 998us/step - loss: 0.1121 - accuracy: 0.9901
Epoch 225/1

4/4 [==============================] - 0s 997us/step - loss: 0.0880 - accuracy: 1.0000
Epoch 297/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0871 - accuracy: 1.0000
Epoch 298/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0872 - accuracy: 1.0000
Epoch 299/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0869 - accuracy: 1.0000
Epoch 300/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0861 - accuracy: 1.0000
Epoch 301/1000
4/4 [==============================] - 0s 992us/step - loss: 0.0857 - accuracy: 1.0000
Epoch 302/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0858 - accuracy: 1.0000
Epoch 303/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0851 - accuracy: 1.0000
Epoch 304/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0855 - accuracy: 1.0000
Epoch 305/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0849 - accuracy: 1.0000
E

4/4 [==============================] - 0s 997us/step - loss: 0.0705 - accuracy: 1.0000
Epoch 378/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0698 - accuracy: 1.0000
Epoch 379/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0702 - accuracy: 1.0000
Epoch 380/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0696 - accuracy: 1.0000
Epoch 381/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0695 - accuracy: 1.0000
Epoch 382/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0696 - accuracy: 1.0000
Epoch 383/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0693 - accuracy: 1.0000
Epoch 384/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0691 - accuracy: 1.0000
Epoch 385/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0690 - accuracy: 1.0000
Epoch 386/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0687 - accuracy: 1.0000
Epo

4/4 [==============================] - 0s 998us/step - loss: 0.0589 - accuracy: 1.0000
Epoch 459/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0593 - accuracy: 1.0000
Epoch 460/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0590 - accuracy: 1.0000
Epoch 461/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0590 - accuracy: 1.0000
Epoch 462/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0583 - accuracy: 1.0000
Epoch 463/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0584 - accuracy: 1.0000
Epoch 464/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0585 - accuracy: 1.0000
Epoch 465/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0579 - accuracy: 1.0000
Epoch 466/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0584 - accuracy: 1.0000
Epoch 467/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0583 - accuracy: 1.0000
E

4/4 [==============================] - 0s 756us/step - loss: 0.0508 - accuracy: 1.0000
Epoch 540/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0507 - accuracy: 1.0000
Epoch 541/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0503 - accuracy: 1.0000
Epoch 542/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0502 - accuracy: 1.0000
Epoch 543/1000
4/4 [==============================] - 0s 756us/step - loss: 0.0500 - accuracy: 1.0000
Epoch 544/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0503 - accuracy: 1.0000
Epoch 545/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0500 - accuracy: 1.0000
Epoch 546/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0502 - accuracy: 1.0000
Epoch 547/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0497 - accuracy: 1.0000
Epoch 548/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0500 - accuracy: 1.0000

4/4 [==============================] - 0s 998us/step - loss: 0.0442 - accuracy: 1.0000
Epoch 621/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0442 - accuracy: 1.0000
Epoch 622/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0443 - accuracy: 1.0000
Epoch 623/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0443 - accuracy: 1.0000
Epoch 624/1000
4/4 [==============================] - 0s 752us/step - loss: 0.0444 - accuracy: 1.0000
Epoch 625/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0440 - accuracy: 1.0000
Epoch 626/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0438 - accuracy: 1.0000
Epoch 627/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0438 - accuracy: 1.0000
Epoch 628/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0437 - accuracy: 1.0000
Epoch 629/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0440 - accuracy: 1.0000
Epo

4/4 [==============================] - 0s 2ms/step - loss: 0.0400 - accuracy: 1.0000
Epoch 702/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0397 - accuracy: 1.0000
Epoch 703/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0396 - accuracy: 1.0000
Epoch 704/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0394 - accuracy: 1.0000
Epoch 705/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0395 - accuracy: 1.0000
Epoch 706/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0392 - accuracy: 1.0000
Epoch 707/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0395 - accuracy: 1.0000
Epoch 708/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0392 - accuracy: 1.0000
Epoch 709/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0391 - accuracy: 1.0000
Epoch 710/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0391 - accuracy: 1.0000
Epoch 711/100

4/4 [==============================] - 0s 997us/step - loss: 0.0357 - accuracy: 1.0000
Epoch 783/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0356 - accuracy: 1.0000
Epoch 784/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0355 - accuracy: 1.0000
Epoch 785/1000
4/4 [==============================] - 0s 996us/step - loss: 0.0355 - accuracy: 1.0000
Epoch 786/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0356 - accuracy: 1.0000
Epoch 787/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0355 - accuracy: 1.0000
Epoch 788/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0355 - accuracy: 1.0000
Epoch 789/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0355 - accuracy: 1.0000
Epoch 790/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0354 - accuracy: 1.0000
Epoch 791/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0354 - accuracy: 1.0000
Epoch 7

4/4 [==============================] - 0s 1ms/step - loss: 0.0326 - accuracy: 1.0000
Epoch 864/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0326 - accuracy: 1.0000
Epoch 865/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0325 - accuracy: 1.0000
Epoch 866/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.0325 - accuracy: 1.0000
Epoch 867/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0324 - accuracy: 1.0000
Epoch 868/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0324 - accuracy: 1.0000
Epoch 869/1000
4/4 [==============================] - 0s 997us/step - loss: 0.0323 - accuracy: 1.0000
Epoch 870/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0324 - accuracy: 1.0000
Epoch 871/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0322 - accuracy: 1.0000
Epoch 872/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0322 - accuracy: 1.0000
Epoch 873/1

4/4 [==============================] - 0s 998us/step - loss: 0.0300 - accuracy: 1.0000
Epoch 945/1000
4/4 [==============================] - 0s 998us/step - loss: 0.0299 - accuracy: 1.0000
Epoch 946/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0299 - accuracy: 1.0000
Epoch 947/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0298 - accuracy: 1.0000
Epoch 948/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0299 - accuracy: 1.0000
Epoch 949/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0298 - accuracy: 1.0000
Epoch 950/1000
4/4 [==============================] - 0s 748us/step - loss: 0.0297 - accuracy: 1.0000
Epoch 951/1000
4/4 [==============================] - 0s 999us/step - loss: 0.0297 - accuracy: 1.0000
Epoch 952/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0297 - accuracy: 1.0000
Epoch 953/1000
4/4 [==============================] - 0s 994us/step - loss: 0.0296 - accuracy: 1.0000
Epoch

In [29]:
print(y_data)

[[0.]
 [0.]
 [3.]
 [0.]
 [0.]
 [0.]
 [0.]
 [3.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [6.]
 [6.]
 [6.]
 [1.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [5.]
 [4.]
 [4.]
 [0.]
 [0.]
 [0.]
 [5.]
 [0.]
 [0.]
 [1.]
 [3.]
 [0.]
 [0.]
 [1.]
 [3.]
 [5.]
 [5.]
 [1.]
 [5.]
 [1.]
 [0.]
 [0.]
 [6.]
 [0.]
 [0.]
 [0.]
 [0.]
 [5.]
 [4.]
 [6.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [6.]
 [3.]
 [0.]
 [0.]
 [2.]
 [6.]
 [1.]
 [1.]
 [2.]
 [6.]
 [3.]
 [1.]
 [0.]
 [6.]
 [3.]
 [1.]
 [5.]
 [4.]
 [2.]
 [2.]
 [3.]
 [0.]
 [0.]
 [1.]
 [0.]
 [5.]
 [0.]
 [6.]
 [1.]]


In [30]:
print(y_data.flatten())

[0. 0. 3. 0. 0. 0. 0. 3. 3. 0. 0. 1. 3. 6. 6. 6. 1. 0. 3. 0. 1. 1. 0. 1.
 5. 4. 4. 0. 0. 0. 5. 0. 0. 1. 3. 0. 0. 1. 3. 5. 5. 1. 5. 1. 0. 0. 6. 0.
 0. 0. 0. 5. 4. 6. 0. 0. 1. 1. 1. 1. 3. 3. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 6. 3. 0. 0. 2. 6. 1. 1. 2. 6. 3. 1. 0. 6. 3. 1. 5. 4. 2. 2. 3. 0. 0. 1.
 0. 5. 0. 6. 1.]
